"""Add scheduler tables

Revision ID: 003
Revises: 002_fix_user_defaults
Create Date: 2025-03-30 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_configs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('organization_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('collect_expenses', sa.Boolean(), nullable=False),
        sa.Column('collect_resources', sa.Boolean(), nullable=False),
        sa.Column('collect_recommendations', sa.Boolean(), nullable=False),
        sa.Column('schedule_type', sa.String(length=20), nullable=False),
        sa.Column('interval_minutes', sa.Integer(), nullable=True),
        sa.Column('cron_expression', sa.String(length=100), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('last_run_at', sa.DateTime(), nullable=True),
        sa.Column('next_run_at', sa.DateTime(), nullable=True),
        sa.Column('consecutive_failures', sa.Integer(), nullable=False),
        sa.Column('max_consecutive_failures', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_configs_organization_id'), 'scheduler_configs', ['organization_id'], unique=False)
    
    op.create_table('scheduler_runs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('scheduler_config_id', sa.String(length=36), nullable=False),
        sa.Column('organization_id', sa.String(length=36), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('collected_expenses', sa.Boolean(), nullable=False),
        sa.Column('collected_resources', sa.Boolean(), nullable=False),
        sa.Column('collected_recommendations', sa.Boolean(), nullable=False),
        sa.Column('expenses_status', sa.String(length=20), nullable=True),
        sa.Column('resources_status', sa.String(length=20), nullable=True),
        sa.Column('recommendations_status', sa.String(length=20), nullable=True),
        sa.Column('expenses_records', sa.Integer(), nullable=False),
        sa.Column('resources_records', sa.Integer(), nullable=False),
        sa.Column('recommendations_records', sa.Integer(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('error_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('trigger_type', sa.String(length=20), nullable=False),
        sa.Column('triggered_by', sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['scheduler_config_id'], ['scheduler_configs.id'], ),
        sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_runs_organization_id'), 'scheduler_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scheduler_runs_scheduler_config_id'), 'scheduler_runs', ['scheduler_config_id'], unique=False)
    
    op.create_table('scheduler_logs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('scheduler_run_id', sa.String(length=36), nullable=False),
        sa.Column('logged_at', sa.DateTime(), nullable=False),
        sa.Column('level', sa.String(length=10), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('data_type', sa.String(length=20), nullable=True),
        sa.Column('cloud_account_id', sa.String(length=36), nullable=True),
        sa.Column('cloud_account_name', sa.String(length=256), nullable=True),
        sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['scheduler_run_id'], ['scheduler_runs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_logs_scheduler_run_id'), 'scheduler_logs', ['scheduler_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_logs_scheduler_run_id'), table_name='scheduler_logs')
    op.drop_table('scheduler_logs')
    op.drop_index(op.f('ix_scheduler_runs_scheduler_config_id'), table_name='scheduler_runs')
    op.drop_index(op.f('ix_scheduler_runs_organization_id'), table_name='scheduler_runs')
    op.drop_table('scheduler_runs')
    op.drop_index(op.f('ix_scheduler_configs_organization_id'), table_name='scheduler_configs')
    op.drop_table('scheduler_configs')
    # ### end Alembic commands ###
