"""Add cost cache tables

Revision ID: 008
Revises: 007
Create Date: 2026-04-03 01:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create cost_cache table
    op.create_table(
        'cost_cache',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('organization_id', sa.String(36), nullable=False),
        sa.Column('cloud_account_id', sa.String(36), nullable=True),
        sa.Column('cache_type', sa.String(20), nullable=False),
        sa.Column('period_start', sa.DateTime(), nullable=False),
        sa.Column('period_end', sa.DateTime(), nullable=False),
        sa.Column('this_month_total', sa.DECIMAL(15, 2), server_default='0', nullable=False),
        sa.Column('last_month_total', sa.DECIMAL(15, 2), server_default='0', nullable=False),
        sa.Column('forecast_total', sa.DECIMAL(15, 2), server_default='0', nullable=False),
        sa.Column('change_percent', sa.DECIMAL(5, 2), server_default='0', nullable=False),
        sa.Column('breakdown_data', sa.JSON(), nullable=True),
        sa.Column('currency', sa.String(3), server_default='USD', nullable=False),
        sa.Column('data_source', sa.String(20), server_default='live', nullable=False),
        sa.Column('collected_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'organization_id', 'cache_type', 'cloud_account_id', 
            'period_start', 'period_end',
            name='uix_cost_cache_lookup'
        ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    )
    
    # Create indexes for cost_cache
    op.create_index(
        'idx_cost_cache_org_lookup',
        'cost_cache',
        ['organization_id', 'cache_type', 'expires_at']
    )
    op.create_index(
        'idx_cost_cache_account',
        'cost_cache',
        ['cloud_account_id', 'expires_at']
    )
    op.create_index(
        'idx_cost_cache_expires',
        'cost_cache',
        ['expires_at']
    )
    
    # Create cost_cache_status table
    op.create_table(
        'cost_cache_status',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('organization_id', sa.String(36), nullable=False),
        sa.Column('last_successful_collection', sa.DateTime(), nullable=True),
        sa.Column('last_collection_status', sa.String(20), server_default='pending', nullable=False),
        sa.Column('accounts_total', sa.Integer(), server_default='0', nullable=False),
        sa.Column('accounts_success', sa.Integer(), server_default='0', nullable=False),
        sa.Column('accounts_failed', sa.Integer(), server_default='0', nullable=False),
        sa.Column('last_error_message', sa.Text(), nullable=True),
        sa.Column('next_collection_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', name='uix_cost_cache_status_org'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    )
    
    # Create index for cost_cache_status
    op.create_index(
        'idx_cost_cache_status_org',
        'cost_cache_status',
        ['organization_id']
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop cost_cache_status table
    op.drop_index('idx_cost_cache_status_org', table_name='cost_cache_status')
    op.drop_table('cost_cache_status')
    
    # Drop cost_cache table
    op.drop_index('idx_cost_cache_expires', table_name='cost_cache')
    op.drop_index('idx_cost_cache_account', table_name='cost_cache')
    op.drop_index('idx_cost_cache_org_lookup', table_name='cost_cache')
    op.drop_table('cost_cache')
    
    # ### end Alembic commands ###