export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  ACCEPT_INVITATION: '/accept-invitation/:token',
  DASHBOARD: '/',
  EXPENSES: '/expenses',
  RECOMMENDATIONS: '/recommendations',
  RECOMMENDATION_DETAIL: '/recommendations/:type',
  RECOMMENDATION_RULES: '/recommendation-rules',
  POOLS: '/pools',
  CLOUD_ACCOUNTS: '/cloud-accounts',
  CLOUD_ACCOUNT_DETAIL: '/cloud-accounts/:id',
  CONNECT_CLOUD_ACCOUNT: '/connect-cloud-account',
  RESOURCES: '/resources',
  RESOURCE_DETAIL: '/resources/:id',
  SCHEDULERS: '/schedulers',
  USERS: '/users',
  SETTINGS: '/settings',
  RBAC: '/rbac',
  EXPORTS: '/exports',
} as const;
